#!/usr/bin/perl

use Getopt::Euclid;

=head1 NAME

analizo metrics - analizo's metric reporting tool

=head1 SYNOPSIS

  analizo metrics [options] [<input> ...]

=head1 DESCRIPTION

analizo metrics analyzes source code in the directories passed as arguments and
procudes a matrics report. Such report is written to the standard output in the
YAML format (see I<http://www.yaml.org/>)

analizo metrics is part of the analizo suite.

=head1 OPTIONS

=over

=item --extractor <extractor>

Define wich extractor method use to analise source code. Default is Doxyparse.

=for Euclid:
  extractor.type: string, extractor =~ /\A\w+\Z/
  extractor.default: 'Doxyparse'

When using the Doxyparse extractor (default), all files matching the languages
supported by doxyparse are processed.

=item --help

Displays a help message on how to use this tool.

=item --list

Displays metric list

=item <input>...

Tells analizo which source code directory(ies) you want to parse.

=for Euclid:
  input.type: readable

=item --output <file>

Use a file as output

=for Euclid:
  file.type: writeable

=item --global-only | -g

Don't output the details about modules: only output global (project-wide) metrics.

=back

=head1 OUTPUT FORMAT

The output is a stream of YAML documents. The first one presents metrics for
the project as a whole. The subsequent ones present per-module metrics, and thus
there will be as many of them as there are modules in your project.

=head1 COPYRIGHT AND AUTHORS

See analizo(1)

=cut

use strict;

use Analizo::Extractor;
use Analizo::Metrics;


if($ARGV{'--list'}){
    my $metrics_handler = new Analizo::Metrics(model => new Analizo::Model);
    my %metrics = $metrics_handler->list_of_metrics();
    foreach my $key (sort keys %metrics){
        print "$key - $metrics{$key}\n";
    }
    exit(0);
}

if($ARGV{'<input>'} =~ /^\s*$/){
    printf("%s: No input files!\n", 'analizo metrics');
    exit(0);
}

my $extractor = Analizo::Extractor->load($ARGV{'--extractor'});
my $metrics = Analizo::Metrics->new(model => $extractor->model);

if ($ARGV{'--global-only'}) {
  $metrics->report_global_metrics_only(1);
}


$extractor->process(@{$ARGV{'<input>'}});

open STDOUT, '>', $ARGV{'--output'} if $ARGV{'--output'};
print $metrics->report;
close STDOUT;

exit(0);
