#!/usr/bin/perl -w

use Pod::Usage;

#use Getopt::Euclid;

=head1 NAME

egypt - a source code analysis suite.

=head1 SYNOPSIS

  egypt <tool> [options] <args>

=head1 DESCRIPTION

egypt is a suite of source code analysis tools, aimed at being
language-independent and extensible. The 'egypt' program is only a starting
point for new users, after you understand how egypt works you will use the
egypt tools through their own programs directly. See TOOLS below for more
information.

=head1 TOOLS

egypt has several individual tools that share a core infrastructure, but do
different analysis and produce different output. They are normally invoked like
this:

  egypt <tool> [OPTIONS] <directory> [<directory> ...]

Although you can invoke egypt tools against one or few files inside a project,
normally it only makes sense to run it against the entire source tree (e.g.
passing "." or "./src" as input directories).

The options and output are specific to each tool, so make sure to read the
corresponding manual for the tool(s) you want.

=head1 OPTIONS

=over

=item --version

Displays version information and exits.

=item --help

Displays help for the 'egypt' command.

=item --usage

Displays usage for the 'egypt' command.

=back

=head1 VERSION

This documentation applies to egypt version 1.8.

=cut

use strict;
use File::Basename;

sub usage {
  pod2usage(-verbose => 1);
  exit(1);
}

if (scalar(@ARGV) == 0) {
  usage();
}

my $base = dirname(__FILE__);
my $command = shift(@ARGV);

if ($command !~ /^[a-z]+$/) {
  usage();
}

my $program = "$base/egypt-$command";
if (! -x $program) {
  printf("\"%s\" is not an egypt command.\n", $command);
  print("\n");
  print("Available commands:\n");
  print("\n");
  for my $cmd_program (sort(glob("$base/egypt-*"))) {
    $cmd_program =~ /^.*egypt-(.*)$/;
    my $cmd = $1;
    printf("  %s\n", $cmd);
  }
  print("\n");

  exit(1);
}

system($program, @ARGV);
exit($? >> 8);
