Feature: Analizo statistics metrics flag

	Scenario: Run analizo histpry with --mean flag
		When I explode t/samples/evolution.tar.gz
	    And I run "analizo metrics-history --mean -o metrics.csv . && cat metrics.csv"
		Then the output must match "_mean,"
		Then the output must not match "_mode,"
	    Then the output must not match "_standard_deviation,"
	    Then the output must not match "_sum,"
	    Then the output must not match "_variance,"
	    Then the output must not match "_quantile_min,"
	    Then the output must not match "_quantile_lower,"
	    Then the output must not match "_quantile_median,"
	    Then the output must not match "_quantile_upper,"
	    Then the output must not match "_quantile_ninety,"
	    Then the output must not match "_quantile_ninety_five,"
	    Then the output must not match "_quantile_max,"
	    Then the output must not match "_kurtosis,"
	    Then the output must not match "_skewness,"

	Scenario: Run analizo histpry with --mode flag
		When I explode t/samples/evolution.tar.gz
	    And I run "analizo metrics-history --mode -o metrics.csv . && cat metrics.csv"
		Then the output must match "_mode,"
		Then the output must not match "_meam,"
	    Then the output must not match "_standard_deviation,"
	    Then the output must not match "_sum,"
	    Then the output must not match "_variance,"
	    Then the output must not match "_quantile_min,"
	    Then the output must not match "_quantile_lower,"
	    Then the output must not match "_quantile_median,"
	    Then the output must not match "_quantile_upper,"
	    Then the output must not match "_quantile_ninety,"
	    Then the output must not match "_quantile_ninety_five,"
	    Then the output must not match "_quantile_max,"
	    Then the output must not match "_kurtosis,"
	    Then the output must not match "_skewness,"
		
	Scenario: Run analizo histpry with --standard flag
		When I explode t/samples/evolution.tar.gz
	    And I run "analizo metrics-history --standard -o metrics.csv . && cat metrics.csv"
		Then the output must match "_standard_deviation,"
		Then the output must not match "_mode,"
	    Then the output must not match "_mean,"
	    Then the output must not match "_sum,"
	    Then the output must not match "_variance,"
	    Then the output must not match "_quantile_min,"
	    Then the output must not match "_quantile_lower,"
	    Then the output must not match "_quantile_median,"
	    Then the output must not match "_quantile_upper,"
	    Then the output must not match "_quantile_ninety,"
	    Then the output must not match "_quantile_ninety_five,"
	    Then the output must not match "_quantile_max,"
	    Then the output must not match "_kurtosis,"
	    Then the output must not match "_skewness,"

	Scenario: Run analizo histpry with --sum flag
		When I explode t/samples/evolution.tar.gz
	    And I run "analizo metrics-history --sum -o metrics.csv . && cat metrics.csv"
		Then the output must match "_sum,"
		Then the output must not match "_mode,"
	    Then the output must not match "_standard_deviation,"
	    Then the output must not match "_mean,"
	    Then the output must not match "_variance,"
	    Then the output must not match "_quantile_min,"
	    Then the output must not match "_quantile_lower,"
	    Then the output must not match "_quantile_median,"
	    Then the output must not match "_quantile_upper,"
	    Then the output must not match "_quantile_ninety,"
	    Then the output must not match "_quantile_ninety_five,"
	    Then the output must not match "_quantile_max,"
	    Then the output must not match "_kurtosis,"
	    Then the output must not match "_skewness,"

	Scenario: Run analizo histpry with --variance flag
		When I explode t/samples/evolution.tar.gz
	    And I run "analizo metrics-history --variance -o metrics.csv . && cat metrics.csv"
		Then the output must match "_variance,"
		Then the output must not match "_mode,"
	    Then the output must not match "_standard_deviation,"
	    Then the output must not match "_sum,"
	    Then the output must not match "_mean,"
	    Then the output must not match "_quantile_min,"
	    Then the output must not match "_quantile_lower,"
	    Then the output must not match "_quantile_median,"
	    Then the output must not match "_quantile_upper,"
	    Then the output must not match "_quantile_ninety,"
	    Then the output must not match "_quantile_ninety_five,"
	    Then the output must not match "_quantile_max,"
	    Then the output must not match "_kurtosis,"
	    Then the output must not match "_skewness,"

	Scenario: Run analizo histpry with --min flag
		When I explode t/samples/evolution.tar.gz
	    And I run "analizo metrics-history --min -o metrics.csv . && cat metrics.csv"
		Then the output must match "_quantile_min,"
		Then the output must not match "_mode,"
	    Then the output must not match "_standard_deviation,"
	    Then the output must not match "_sum,"
	    Then the output must not match "_variance,"
	    Then the output must not match "_mean,"
	    Then the output must not match "_quantile_lower,"
	    Then the output must not match "_quantile_median,"
	    Then the output must not match "_quantile_upper,"
	    Then the output must not match "_quantile_ninety,"
	    Then the output must not match "_quantile_ninety_five,"
	    Then the output must not match "_quantile_max,"
	    Then the output must not match "_kurtosis,"
	    Then the output must not match "_skewness,"

	Scenario: Run analizo histpry with --lower flag
		When I explode t/samples/evolution.tar.gz
	    And I run "analizo metrics-history --lower -o metrics.csv . && cat metrics.csv"
		Then the output must match "_quantile_lower,"
		Then the output must not match "_meam,"
	    Then the output must not match "_standard_deviation,"
	    Then the output must not match "_sum,"
	    Then the output must not match "_variance,"
	    Then the output must not match "_quantile_min,"
	    Then the output must not match "_mode,"
	    Then the output must not match "_quantile_median,"
	    Then the output must not match "_quantile_upper,"
	    Then the output must not match "_quantile_ninety,"
	    Then the output must not match "_quantile_ninety_five,"
	    Then the output must not match "_quantile_max,"
	    Then the output must not match "_kurtosis,"
	    Then the output must not match "_skewness,"
		
	Scenario: Run analizo histpry with --median flag
		When I explode t/samples/evolution.tar.gz
	    And I run "analizo metrics-history --median -o metrics.csv . && cat metrics.csv"
		Then the output must match "_quantile_median,"
		Then the output must not match "_mode,"
	    Then the output must not match "_mean,"
	    Then the output must not match "_sum,"
	    Then the output must not match "_variance,"
	    Then the output must not match "_quantile_min,"
	    Then the output must not match "_quantile_lower,"
	    Then the output must not match "_standard_deviation,"
	    Then the output must not match "_quantile_upper,"
	    Then the output must not match "_quantile_ninety,"
	    Then the output must not match "_quantile_ninety_five,"
	    Then the output must not match "_quantile_max,"
	    Then the output must not match "_kurtosis,"
	    Then the output must not match "_skewness,"

	Scenario: Run analizo histpry with --upper flag
		When I explode t/samples/evolution.tar.gz
	    And I run "analizo metrics-history --upper -o metrics.csv . && cat metrics.csv"
		Then the output must match "_quantile_upper,"
		Then the output must not match "_mode,"
	    Then the output must not match "_standard_deviation,"
	    Then the output must not match "_mean,"
	    Then the output must not match "_variance,"
	    Then the output must not match "_quantile_min,"
	    Then the output must not match "_quantile_lower,"
	    Then the output must not match "_quantile_median,"
	    Then the output must not match "_sum,"
	    Then the output must not match "_quantile_ninety,"
	    Then the output must not match "_quantile_ninety_five,"
	    Then the output must not match "_quantile_max,"
	    Then the output must not match "_kurtosis,"
	    Then the output must not match "_skewness,"

	Scenario: Run analizo histpry with --ninety flag
		When I explode t/samples/evolution.tar.gz
	    And I run "analizo metrics-history --ninety -o metrics.csv . && cat metrics.csv"
		Then the output must match "_quantile_ninety,"
		Then the output must not match "_mode,"
	    Then the output must not match "_standard_deviation,"
	    Then the output must not match "_sum,"
	    Then the output must not match "_mean,"
	    Then the output must not match "_quantile_min,"
	    Then the output must not match "_quantile_lower,"
	    Then the output must not match "_quantile_median,"
	    Then the output must not match "_quantile_upper,"
	    Then the output must not match "_variance,"
	    Then the output must not match "_quantile_ninety_five,"
	    Then the output must not match "_quantile_max,"
	    Then the output must not match "_kurtosis,"
	    Then the output must not match "_skewness,"

	Scenario: Run analizo histpry with --ninety_five flag
		When I explode t/samples/evolution.tar.gz
	    And I run "analizo metrics-history --ninety_five -o metrics.csv . && cat metrics.csv"
		Then the output must match "_quantile_ninety_five,"
		Then the output must not match "_mode,"
	    Then the output must not match "_standard_deviation,"
	    Then the output must not match "_sum,"
	    Then the output must not match "_variance,"
	    Then the output must not match "_quantile_min,"
	    Then the output must not match "_quantile_lower,"
	    Then the output must not match "_quantile_median,"
	    Then the output must not match "_quantile_upper,"
	    Then the output must not match "_quantile_ninety,"
	    Then the output must not match "_mean,"
	    Then the output must not match "_quantile_max,"
	    Then the output must not match "_kurtosis,"
	    Then the output must not match "_skewness,"

	Scenario: Run analizo histpry with --max flag
		When I explode t/samples/evolution.tar.gz
	    And I run "analizo metrics-history --max -o metrics.csv . && cat metrics.csv"
		Then the output must match "_quantile_max,"
		Then the output must not match "_meam,"
	    Then the output must not match "_standard_deviation,"
	    Then the output must not match "_sum,"
	    Then the output must not match "_variance,"
	    Then the output must not match "_quantile_min,"
	    Then the output must not match "_quantile_lower,"
	    Then the output must not match "_quantile_median,"
	    Then the output must not match "_quantile_upper,"
	    Then the output must not match "_quantile_ninety,"
	    Then the output must not match "_quantile_ninety_five,"
	    Then the output must not match "_mode,"
	    Then the output must not match "_kurtosis,"
	    Then the output must not match "_skewness,"
		
	Scenario: Run analizo histpry with --kurtosis flag
		When I explode t/samples/evolution.tar.gz
	    And I run "analizo metrics-history --kurtosis -o metrics.csv . && cat metrics.csv"
		Then the output must match "_kurtosis,"
		Then the output must not match "_mode,"
	    Then the output must not match "_mean,"
	    Then the output must not match "_sum,"
	    Then the output must not match "_variance,"
	    Then the output must not match "_quantile_min,"
	    Then the output must not match "_quantile_lower,"
	    Then the output must not match "_quantile_median,"
	    Then the output must not match "_quantile_upper,"
	    Then the output must not match "_quantile_ninety,"
	    Then the output must not match "_quantile_ninety_five,"
	    Then the output must not match "_quantile_max,"
	    Then the output must not match "_standard_deviation,"
	    Then the output must not match "_skewness,"

	Scenario: Run analizo histpry with --skewness flag
		When I explode t/samples/evolution.tar.gz
	    And I run "analizo metrics-history --skewness -o metrics.csv . && cat metrics.csv"
		Then the output must match "_skewness,"
		Then the output must not match "_mode,"
	    Then the output must not match "_standard_deviation,"
	    Then the output must not match "_mean,"
	    Then the output must not match "_variance,"
	    Then the output must not match "_quantile_min,"
	    Then the output must not match "_quantile_lower,"
	    Then the output must not match "_quantile_median,"
	    Then the output must not match "_quantile_upper,"
	    Then the output must not match "_quantile_ninety,"
	    Then the output must not match "_quantile_ninety_five,"
	    Then the output must not match "_quantile_max,"
	    Then the output must not match "_kurtosis,"
	    Then the output must not match "_sum,"